apiVersion: v1
data:
  .dockerconfigjson: ##DOCKER_SECRET_CONFIG##
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: logistics
type: kubernetes.io/dockerconfigjson